[general]
live_config_reload = true

[window]
# decorations = "None"
dynamic_padding = false
padding.x = 0
padding.y = 0

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[colors.primary]
background = '#1b181b'
foreground = '#ab9bab'

[colors.cursor]
text = '#1b181b'
cursor = '#7b59c0'

[colors.normal]
black = '#1b181b'
red = '#ca402b'
green = '#918b3b'
yellow = '#bb8a35'
blue = '#516aec'
magenta = '#7b59c0'
cyan = '#159393'
white = '#ab9bab'

[colors.bright]
black = '#776977'
red = '#ca402b'
green = '#918b3b'
yellow = '#bb8a35'
blue = '#516aec'
magenta = '#7b59c0'
cyan = '#159393'
white = '#f7f3f7'

[[colors.indexed_colors]]
index = 16
color = "#a65926"

[[colors.indexed_colors]]
index = 17
color = "#cc33cc"

[[colors.indexed_colors]]
index = 18
color = "#292329"

[[colors.indexed_colors]]
index = 19
color = "#695d69"

[[colors.indexed_colors]]
index = 20
color = "#9e8f9e"

[[colors.indexed_colors]]
index = 21
color = "#d8cad8"
