[general]
live_config_reload = true

[window]
padding.x = 0
padding.y = 0

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[colors.primary]
background = '0x1b181b'
foreground = '0xab9bab'

[colors.cursor]
text = '0x1b181b'
cursor = '0xab9bab'

[colors.normal]
black = '0x1b181b'
red = '0xca402b'
green = '0x918b3b'
yellow = '0xbb8a35'
blue = '0x516aec'
magenta = '0x7b59c0'
cyan = '0x159393'
white = '0xab9bab'

[colors.bright]
black = '0x776977'
red = '0xca402b'
green = '0x918b3b'
yellow = '0xbb8a35'
blue = '0x516aec'
magenta = '0x7b59c0'
cyan = '0x159393'
white = '0xf7f3f7'

[[colors.indexed_colors]]
index = 16
color = "0xa65926"

[[colors.indexed_colors]]
index = 17
color = "0xcc33cc"

[[colors.indexed_colors]]
index = 18
color = "0x292329"

[[colors.indexed_colors]]
index = 19
color = "0x695d69"

[[colors.indexed_colors]]
index = 20
color = "0x9e8f9e"

[[colors.indexed_colors]]
index = 21
color = "0xd8cad8"
